# Phoenix -- a compiler-compiler.
#
#   make           build bin/phx
#   make test      build and run the tests
#   make clean

CC      ?= cc
CFLAGS  ?= -std=c11 -O2 -g
WARN     = -Wall -Wextra -Wpedantic -Wshadow -Wstrict-prototypes \
           -Wmissing-prototypes -Wno-unused-parameter

# The **runtime** is what *runs* a description: the scanner, the matcher, the
# evaluator and the library. A generated compiler is these files plus its own
# tables, so they are embedded in `phx` as text and written into every compiler
# it emits -- which is why `cc pascal.c -o cpas` needs no flags and no headers.
#
# The **front** is what *reads* a description, and a generated compiler has no
# use for it: it will never see a `.phx` file.
RUNTIME = phoenix/support.c phoenix/eval.c phoenix/library.c \
          phoenix/lex.c phoenix/parse.c phoenix/include.c phoenix/run.c

FRONT   = phoenix/grammar.c phoenix/check.c phoenix/expr.c phoenix/pass.c \
          phoenix/emit.c phoenix/main.c

SRC = $(RUNTIME) $(FRONT)
HDR = phoenix/phx.h phoenix/reader.h

all: bin/phx

# The runtime, as a C string literal, so that phx carries its own runtime and a
# generated compiler is one file. `#include "phx.h"` is dropped because the
# header is prepended; the guard in it makes a second copy harmless anyway.
phoenix/runtime.h: $(RUNTIME) phoenix/phx.h
	@echo '/* Generated by the Makefile from phx.h and the runtime. */' > $@
	@echo '/* The runtime is one translation unit in a generated compiler, so' >> $@
	@echo ' * a literal this long is unavoidable and is what every compiler in' >> $@
	@echo ' * use supports; only the standard'"'"'s stated minimum is smaller. */' >> $@
	@echo '#if defined(__GNUC__) || defined(__clang__)' >> $@
	@echo '#pragma GCC diagnostic ignored "-Woverlength-strings"' >> $@
	@echo '#endif' >> $@
	@echo 'static const char runtime_source[] =' >> $@
	@cat phoenix/phx.h $(RUNTIME) \
	  | grep -v '^#include "phx.h"' \
	  | awk '{ gsub(/\\/, "\\\\"); gsub(/"/, "\\\""); \
	           print "\"" $$0 "\\n\"" }' >> $@
	@echo ';' >> $@

phoenix/emit.c: phoenix/runtime.h

bin/phx: $(SRC) $(HDR) phoenix/runtime.h
	@mkdir -p bin
	$(CC) $(CFLAGS) $(WARN) -o $@ $(SRC)

test: bin/phx
	@tests/run.sh

clean:
	rm -rf bin phoenix/runtime.h

.PHONY: all test clean
